
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  byfn:
    external:
      name: vice-network

services:
  explorerdb.vice.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.vice.com
    hostname: explorerdb.vice.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 6432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - byfn
    
  explorer.vice.com:
    image: hyperledger/explorer:latest
    container_name: explorer.vice.com
    hostname: explorer.vice.com
    environment:
      - DATABASE_HOST=explorerdb.vice.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ../vice_config.json:/opt/explorer/app/platform/fabric/config.json
      - ../connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ../crypto-config:/tmp/crypto
      - ./walletstore:/opt/explorer/wallet
    ports:
      - 8090:8090
    depends_on:
      explorerdb.vice.com:
        condition: service_healthy
    networks:
      - byfn
